version: '3'

services:
  database:
    image: mariadb
    volumes:
    - ~/.docker/${APP_NAME}:/var/lib/mysql
    ports:
    - 3305:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
      TZ: ${TZ}
  workspace:
    build: ./
    ports:
    - 85:80
    environment:
      TZ: ${TZ}
    expose:
    - 85
    volumes:
    - ./:/usr/share/nginx/html
    links:
    - database
